### ISSUE TITLE
Super EverDrive & SD2SNES SMDB.txt: duplicate file extension: Hyper V-Ball (S) (V1.0) (Sayans).smc.sfc

### ISSUE THREAD

**Issue by tjanas** [SmokeMonsterPacks/EverDrive-Packs-Lists-Database#138]
Either drop .smc or drop .sfc in the filename:
`SD2SNES/4 Translations/Non-English/Spanish/Hyper V-Ball (S) (V1.0) (Sayans).smc.sfc`

**Comment by frederic-mahe** [comment]
fixed

**Comment by tjanas** [comment]
I still see the duplicate extension. Do you have a commit for this fix?

**Comment by frederic-mahe** [comment]
you are right. Here is the fix: https://github.com/SmokeMonsterPacks/EverDrive-Packs-Lists-Database/commit/5d3f9fd1db57ed307c2391714f0fdbc4347466a6
